### ISSUE TITLE
请问vuecli2 的项目如何迁移到single-spa

### ISSUE THREAD

**Issue by guowenzhuang** [CanopyTax/vue-cli-plugin-single-spa#4]

**Comment by guowenzhuang** [comment]
我把项目升级到vuecli3 这个问题解决了 
但是我又碰到了新的问题
icon不加载了
![image](https://user-images.githubusercontent.com/40003142/62671930-4d6d0200-b9cb-11e9-8f2c-7a946eace0b8.png)
我用的是iview-admin 想把他作为 single-spa的一个app应用

**Comment by guowenzhuang** [comment]
![image](https://user-images.githubusercontent.com/40003142/62671975-74c3cf00-b9cb-11e9-8e92-ec212d659ccd.png)

**Comment by guowenzhuang** [comment]
他正确的地址是  localhost:8007/99ac3308dd8ee14f749f51538d0d5b9e.woff
8007 port 是我的应用
我不知道该怎么去配置

**Comment by joeldenning** [comment]
@guowenzhuang this looks like it is related to [webpack public path](https://webpack.js.org/guides/public-path/#root). The webpack public path controls where code splits are downloaded from. In your case, since the public path isn't set, it's attempting to download from localhost:5000, but you likely need it to download from a different port on localhost.

To fix this, you need to set the public path ["On The Fly"](https://webpack.js.org/guides/public-path/#on-the-fly). For example:

```js
__webpack_public_path__ = 'http://localhost:8080/'
```

See [here](https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/app1/src/set-public-path.js) for an example that sets the public path correctly. Make sure that you set the public path **before any other code executes in your bundle**. You can do this by doing it in its own file set-public-path.js, that is [**imported before any other file**](https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/app1/src/main.js#L1).
